version: "3.9"

services:
  server:
    build: .
    container_name: metrics
    image: metrics:latest

    ports:
      - "20552:20552"

    command: uvicorn app:app --host 0.0.0.0 --port 20552 --reload

    volumes:
      - .:/workspace
      - /dev_storage/metrics:/data

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
